version: "3.1"
services:
  moodle:
    container_name: moodle
    image: bitnami/moodle:latest
    ports:
      - 80:80
    restart: always
    environment:
      MOODLE_DATABASE_HOST: <IP-Private> # IP privada de la base de datos
      MOODLE_DATABASE_USER: moodle_user
      MOODLE_DATABASE_PASSWORD: 12345
      MOODLE_DATABASE_NAME: moodle_db
    volumes:
      - /mnt/moodle:/bitnami/moodle